AWSTemplateFormatVersion: '2010-09-09'
Description: 'DevRAG-Lite Infrastructure - Free Tier Optimized'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  
  DatabasePassword:
    Type: String
    Description: Database password for PostgreSQL
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Default: TempPassword123!

Resources:
  # S3 Bucket for document storage
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'devrag-${Environment}-docs-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # RDS PostgreSQL instance (Free Tier)
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub 'devrag-${Environment}-db'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '13.13'
      MasterUsername: postgres
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 20
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup


  # Security Group for RDS
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for DevRAG database
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  # Security Group for Lambda
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for DevRAG Lambda functions

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket for document storage
    Value: !Ref DocumentBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  DatabaseEndpoint:
    Description: RDS PostgreSQL endpoint
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
      